### PR TITLE
Fix clippy warnings

### LINKED ISSUE #163: Clippy CI build fails
The Clippy CI build currently fails, presumably because a new Clippy version has been pulled in. It would be nice to get this fixed (either by following what Clippy says or by silencing those warnings; haven't looked into it, so don't know what would be appropriate). Any pull request doing so would be very welcome!

### PR DESCRIPTION
**Pull request by dbrgn**
This should hopefully fix all issues reported by Clippy.

Resolves #163.

### CODE REVIEW

File: src/serial.rs [hunk 1]
```diff
@@ -339,7 +338,7 @@ macro_rules! usart {
                     let mut brr = mantissa << 4 | fraction;
 
                     if stringify!($usartX) == "lpuart1" {
-                        brr = brr*256
+                        brr *= 256
```
Comment (dbrgn) [inline src/serial.rs:341]: "lpuart1 goes brr" 😂

**Review by hannobraun — APPROVED** [review]
Thank you, @dbrgn, looks great!
